# Generated by Django 3.2 on 2024-03-09 06:40

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('AN', 'Anonymous'), ('US', 'User'), ('MD', 'Moderator'), ('AD', 'Admin'), ('SU', 'Superuser')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.validate_name]),
        ),
    ]
